<?php

declare(strict_types=1);

namespace DbMigrations;

use Phinx\Migration\AbstractMigration;

final class RuleData extends AbstractMigration
{
    public function up()
    {
        $currentTime = date("Y-m-d H:i:s");
        $ruleRows = [
            [
                'id' => 1,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 2,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/home',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 3,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/add',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 4,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/save',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 5,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/read',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 6,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 7,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/delete',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 8,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/restore',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 43,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/i18n',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 44,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/i18n_update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 9,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 10,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/home',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 11,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/add',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 12,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/save',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 13,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/read',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 14,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 15,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/delete',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 16,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/restore',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 45,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/i18n',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 46,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/i18n_update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 17,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 18,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/home',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 19,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/add',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 20,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/save',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 21,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/read',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 22,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 23,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/delete',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 24,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/restore',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 47,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/i18n',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 48,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/i18n_update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 25,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 26,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/home',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 27,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/add',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 28,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/save',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 29,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/read',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 30,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 31,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/delete',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 32,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/restore',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 49,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/i18n',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 50,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/i18n_update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 33,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 34,
                'parent_id'  => 33,
                'rule_path' => 'api/model/home',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 35,
                'parent_id'  => 33,
                'rule_path' => 'api/model/add',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 36,
                'parent_id'  => 33,
                'rule_path' => 'api/model/save',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 37,
                'parent_id'  => 33,
                'rule_path' => 'api/model/read',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 38,
                'parent_id'  => 33,
                'rule_path' => 'api/model/update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 39,
                'parent_id'  => 33,
                'rule_path' => 'api/model/delete',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 40,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/login',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 41,
                'parent_id'  => 33,
                'rule_path' => 'api/model/design',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 42,
                'parent_id'  => 33,
                'rule_path' => 'api/model/design_update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 51,
                'parent_id'  => 33,
                'rule_path' => 'api/model/i18n',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
            [
                'id' => 52,
                'parent_id'  => 33,
                'rule_path' => 'api/model/i18n_update',
                'create_time'  => $currentTime,
                'update_time'  => $currentTime,
            ],
        ];
        $this->table('auth_rule')->insert($ruleRows)->save();

        $ruleI18nRows = [
            [
                'original_id' => 1,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 2,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Home',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 3,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Add',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 4,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Save',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 5,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Read',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 6,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 7,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Delete',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 8,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Restore',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 43,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin I18n',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 44,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin I18n Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 9,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 10,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Home',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 11,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Add',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 12,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Save',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 13,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Read',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 14,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 15,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Delete',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 16,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Restore',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 45,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group I18n',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 46,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group I18n Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 17,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 18,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Home',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 19,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Add',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 20,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Save',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 21,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Read',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 22,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 23,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Delete',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 24,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Restore',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 47,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule I18n',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 48,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule I18n Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 25,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 26,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Home',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 27,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Add',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 28,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Save',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 29,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Read',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 30,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 31,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Delete',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 32,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Restore',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 49,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu I18n',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 50,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu I18n Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 33,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 34,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Home',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 35,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Add',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 36,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Save',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 37,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Read',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 38,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 39,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Delete',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 40,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Login',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 41,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Design',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 42,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Design Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 51,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model I18n',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 52,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model I18n Update',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 1,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 2,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员列表',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 3,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员添加',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 4,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员保存',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 5,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员读取',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 6,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员更新',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 7,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员删除',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 8,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员恢复',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 43,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员国际化',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 44,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员国际化编辑',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 9,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 10,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组列表',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 11,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组添加',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 12,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组保存',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 13,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组读取',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 14,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组更新',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 15,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组删除',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 16,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组恢复',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 45,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组国际化',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 46,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组国际化编辑',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 17,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 18,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限列表',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 19,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限添加',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 20,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限保存',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 21,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限读取',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 22,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限更新',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 23,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限删除',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 24,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限恢复',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 47,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限国际化',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 48,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限国际化编辑',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 25,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 26,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单列表',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 27,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单添加',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 28,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单保存',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 29,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单读取',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 30,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单更新',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 31,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单删除',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 32,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单恢复',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 49,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单国际化',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 50,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单国际化编辑',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 33,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 34,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型列表',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 35,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型添加',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 36,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型保存',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 37,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型读取',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 38,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型更新',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 39,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型删除',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 40,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员登陆',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 41,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型设计',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 42,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型设计更新',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 51,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型国际化',
                'translate_time' => $currentTime,
            ],
            [
                'original_id' => 52,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型国际化编辑',
                'translate_time' => $currentTime,
            ],
        ];
        $this->table('auth_rule_i18n')->insert($ruleI18nRows)->save();
    }

    public function down()
    {
        $this->execute('DELETE FROM auth_rule');
        $this->execute('DELETE FROM auth_rule_i18n');
    }
}
