<?php

declare(strict_types=1);

namespace DbMigrations;

use Phinx\Migration\AbstractMigration;

final class RuleData extends AbstractMigration
{
    public function up()
    {
        $ruleRows = [
            [
                'id' => 1,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 2,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/home',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/add',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 4,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/save',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 5,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/read',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 6,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/update',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 7,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/delete',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 8,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/restore',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 9,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 10,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/home',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 11,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/add',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 12,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/save',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 13,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/read',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 14,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/update',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 15,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/delete',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 16,
                'parent_id'  => 9,
                'rule_path' => 'api/auth_group/restore',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 17,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 18,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/home',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 19,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/add',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 20,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/save',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 21,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/read',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 22,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/update',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 23,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/delete',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 24,
                'parent_id'  => 17,
                'rule_path' => 'api/auth_rule/restore',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 25,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 26,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/home',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 27,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/add',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 28,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/save',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 29,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/read',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 30,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/update',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 31,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/delete',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 32,
                'parent_id'  => 25,
                'rule_path' => 'api/menu/restore',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 33,
                'parent_id'  => 0,
                'rule_path' => '',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 34,
                'parent_id'  => 33,
                'rule_path' => 'api/model/home',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 35,
                'parent_id'  => 33,
                'rule_path' => 'api/model/add',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 36,
                'parent_id'  => 33,
                'rule_path' => 'api/model/save',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 37,
                'parent_id'  => 33,
                'rule_path' => 'api/model/read',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 38,
                'parent_id'  => 33,
                'rule_path' => 'api/model/update',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 39,
                'parent_id'  => 33,
                'rule_path' => 'api/model/delete',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 40,
                'parent_id'  => 1,
                'rule_path' => 'api/admin/login',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 41,
                'parent_id'  => 33,
                'rule_path' => 'api/model/design',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 42,
                'parent_id'  => 33,
                'rule_path' => 'api/model/design_update',
                'create_time'  => date("Y-m-d H:i:s"),
                'update_time'  => date("Y-m-d H:i:s"),
            ],
        ];
        $this->table('auth_rule')->insert($ruleRows)->save();

        $ruleI18nRows = [
            [
                '_id' => 1,
                'original_id' => 1,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin',
            ],
            [
                '_id' => 2,
                'original_id' => 2,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Home',
            ],
            [
                '_id' => 3,
                'original_id' => 3,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Add',
            ],
            [
                '_id' => 4,
                'original_id' => 4,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Save',
            ],
            [
                '_id' => 5,
                'original_id' => 5,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Read',
            ],
            [
                '_id' => 6,
                'original_id' => 6,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Update',
            ],
            [
                '_id' => 7,
                'original_id' => 7,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Delete',
            ],
            [
                '_id' => 8,
                'original_id' => 8,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Restore',
            ],
            [
                '_id' => 9,
                'original_id' => 9,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group',
            ],
            [
                '_id' => 10,
                'original_id' => 10,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Home',
            ],
            [
                '_id' => 11,
                'original_id' => 11,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Add',
            ],
            [
                '_id' => 12,
                'original_id' => 12,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Save',
            ],
            [
                '_id' => 13,
                'original_id' => 13,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Read',
            ],
            [
                '_id' => 14,
                'original_id' => 14,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Update',
            ],
            [
                '_id' => 15,
                'original_id' => 15,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Delete',
            ],
            [
                '_id' => 16,
                'original_id' => 16,
                'lang_code' => 'en-us',
                'rule_title'  => 'Group Restore',
            ],
            [
                '_id' => 17,
                'original_id' => 17,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule',
            ],
            [
                '_id' => 18,
                'original_id' => 18,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Home',
            ],
            [
                '_id' => 19,
                'original_id' => 19,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Add',
            ],
            [
                '_id' => 20,
                'original_id' => 20,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Save',
            ],
            [
                '_id' => 21,
                'original_id' => 21,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Read',
            ],
            [
                '_id' => 22,
                'original_id' => 22,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Update',
            ],
            [
                '_id' => 23,
                'original_id' => 23,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Delete',
            ],
            [
                '_id' => 24,
                'original_id' => 24,
                'lang_code' => 'en-us',
                'rule_title'  => 'Rule Restore',
            ],
            [
                '_id' => 25,
                'original_id' => 25,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu',
            ],
            [
                '_id' => 26,
                'original_id' => 26,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Home',
            ],
            [
                '_id' => 27,
                'original_id' => 27,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Add',
            ],
            [
                '_id' => 28,
                'original_id' => 28,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Save',
            ],
            [
                '_id' => 29,
                'original_id' => 29,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Read',
            ],
            [
                '_id' => 30,
                'original_id' => 30,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Update',
            ],
            [
                '_id' => 31,
                'original_id' => 31,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Delete',
            ],
            [
                '_id' => 32,
                'original_id' => 32,
                'lang_code' => 'en-us',
                'rule_title'  => 'Menu Restore',
            ],
            [
                '_id' => 33,
                'original_id' => 33,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model',
            ],
            [
                '_id' => 34,
                'original_id' => 34,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Home',
            ],
            [
                '_id' => 35,
                'original_id' => 35,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Add',
            ],
            [
                '_id' => 36,
                'original_id' => 36,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Save',
            ],
            [
                '_id' => 37,
                'original_id' => 37,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Read',
            ],
            [
                '_id' => 38,
                'original_id' => 38,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Update',
            ],
            [
                '_id' => 39,
                'original_id' => 39,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Delete',
            ],
            [
                '_id' => 40,
                'original_id' => 40,
                'lang_code' => 'en-us',
                'rule_title'  => 'Admin Login',
            ],
            [
                '_id' => 41,
                'original_id' => 41,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Design',
            ],
            [
                '_id' => 42,
                'original_id' => 42,
                'lang_code' => 'en-us',
                'rule_title'  => 'Model Design Update',
            ],
            [
                '_id' => 43,
                'original_id' => 1,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员',
            ],
            [
                '_id' => 44,
                'original_id' => 2,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员列表',
            ],
            [
                '_id' => 45,
                'original_id' => 3,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员添加',
            ],
            [
                '_id' => 46,
                'original_id' => 4,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员保存',
            ],
            [
                '_id' => 47,
                'original_id' => 5,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员读取',
            ],
            [
                '_id' => 48,
                'original_id' => 6,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员更新',
            ],
            [
                '_id' => 49,
                'original_id' => 7,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员删除',
            ],
            [
                '_id' => 50,
                'original_id' => 8,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员恢复',
            ],
            [
                '_id' => 51,
                'original_id' => 9,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组',
            ],
            [
                '_id' => 52,
                'original_id' => 10,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组列表',
            ],
            [
                '_id' => 53,
                'original_id' => 11,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组添加',
            ],
            [
                '_id' => 54,
                'original_id' => 12,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组保存',
            ],
            [
                '_id' => 55,
                'original_id' => 13,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组读取',
            ],
            [
                '_id' => 56,
                'original_id' => 14,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组更新',
            ],
            [
                '_id' => 57,
                'original_id' => 15,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组删除',
            ],
            [
                '_id' => 58,
                'original_id' => 16,
                'lang_code' => 'zh-cn',
                'rule_title'  => '用户组恢复',
            ],
            [
                '_id' => 59,
                'original_id' => 17,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限',
            ],
            [
                '_id' => 60,
                'original_id' => 18,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限列表',
            ],
            [
                '_id' => 61,
                'original_id' => 19,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限添加',
            ],
            [
                '_id' => 62,
                'original_id' => 20,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限保存',
            ],
            [
                '_id' => 63,
                'original_id' => 21,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限读取',
            ],
            [
                '_id' => 64,
                'original_id' => 22,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限更新',
            ],
            [
                '_id' => 65,
                'original_id' => 23,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限删除',
            ],
            [
                '_id' => 66,
                'original_id' => 24,
                'lang_code' => 'zh-cn',
                'rule_title'  => '权限恢复',
            ],
            [
                '_id' => 67,
                'original_id' => 25,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单',
            ],
            [
                '_id' => 68,
                'original_id' => 26,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单列表',
            ],
            [
                '_id' => 69,
                'original_id' => 27,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单添加',
            ],
            [
                '_id' => 70,
                'original_id' => 28,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单保存',
            ],
            [
                '_id' => 71,
                'original_id' => 29,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单读取',
            ],
            [
                '_id' => 72,
                'original_id' => 30,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单更新',
            ],
            [
                '_id' => 73,
                'original_id' => 31,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单删除',
            ],
            [
                '_id' => 74,
                'original_id' => 32,
                'lang_code' => 'zh-cn',
                'rule_title'  => '菜单恢复',
            ],
            [
                '_id' => 75,
                'original_id' => 33,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型',
            ],
            [
                '_id' => 76,
                'original_id' => 34,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型列表',
            ],
            [
                '_id' => 77,
                'original_id' => 35,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型添加',
            ],
            [
                '_id' => 78,
                'original_id' => 36,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型保存',
            ],
            [
                '_id' => 79,
                'original_id' => 37,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型读取',
            ],
            [
                '_id' => 80,
                'original_id' => 38,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型更新',
            ],
            [
                '_id' => 81,
                'original_id' => 39,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型删除',
            ],
            [
                '_id' => 82,
                'original_id' => 40,
                'lang_code' => 'zh-cn',
                'rule_title'  => '管理员登陆',
            ],
            [
                '_id' => 83,
                'original_id' => 41,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型设计',
            ],
            [
                '_id' => 84,
                'original_id' => 42,
                'lang_code' => 'zh-cn',
                'rule_title'  => '模型设计更新',
            ],
        ];
        $this->table('auth_rule_i18n')->insert($ruleI18nRows)->save();
    }

    public function down()
    {
        $this->execute('DELETE FROM auth_rule');
        $this->execute('DELETE FROM auth_rule_i18n');
    }
}
