<?php

return [
    'reserved_field' => [
        'id',
        'title',
        'pathname',
        'list_order',
        'create_time',
        'update_time',
        'delete_time',
        'status',
        '_id',
        'original_id',
        'lang_code',
        'translate_time',
        'parent_id',
    ],
    'reserved_table' => [
        'admin',
        'admin_i18n',
        'auth_group',
        'auth_group_i18n',
        'auth_admin_group',
        'auth_rule',
        'auth_rule_i18n',
        'auth_group_rule',
        'menu',
        'menu_i18n',
        'model',
        'model_i18n',
        'migrations',
        'revision',
    ],
];
